### PR TITLE
add failing test where secrets.yaml is not found and fix it

### PR DESCRIPTION
**Pull request by basnijholt**
This (currently failing) test reproduces the problem described in https://github.com/robmarkcole/HASS-data-detective/issues/85.

@balloob, would you know where this goes wrong?

I have added a recursive search in https://github.com/robmarkcole/HASS-data-detective/pull/119/commits/aa1fcfb7a2ce312a6c8e8a8d6104ea042d65d6bd, however, I do not know if this is the proper solution.

### CODE REVIEW

**Comment by basnijholt** [comment]
I have now implemented the same recursion rules as in Home Assistant (see this https://www.home-assistant.io/docs/configuration/secrets/#debugging-secrets).

I think how I did it is a fine solution.

**Comment by basnijholt** [comment]
I have found another failing test with
```
nested_without_secret: !include includes/without_secret.yaml
```
Which was reported before https://github.com/robmarkcole/HASS-data-detective/issues/87.

**Comment by balloob** [comment]
I haven't used this in forever. I don't know what's going on . We should indeed follow the HA recursion rules (or even better, import them directly?)

**Comment by robmarkcole** [comment]
Can you fix the test?

**Comment by basnijholt** [comment]
@robmarkcole, the test isn't broken, the code is broken and the tests shows the failing case.

**Comment by robmarkcole** [comment]
OK LGTM, thanks!

**Pull request merged**
